#!/usr/bin/env ruby

require File.join(File.dirname(__FILE__), "../lib/quilt")

# specify the database server url here
DB = "http://127.0.0.1:5984"

# couch fs will be mounted here
# eg: app/127.0.0.1:5984
MOUNT_DIR = File.expand_path(File.join(File.dirname(__FILE__), '..', 'app', File.basename(DB)))

# create mount dir unless exists
Dir.mkdir(MOUNT_DIR) unless File.directory?(MOUNT_DIR)

# init couch dir
couchdir = Quilt.new(DB)

FuseFS.set_root(couchdir)
FuseFS.mount_under MOUNT_DIR

trap("INT") do
  puts "ancelling..."
  FuseFS.unmount
  FuseFS.exit
  puts "Bye."
end

puts "Quilt is running on #{MOUNT_DIR}"
FuseFS.run
