#!/usr/bin/env ruby

require 'fusefs'
require File.join(File.dirname(__FILE__), "../lib/quilt")

# specify the database name here
DB_NAME = "nashi-01-development"

# couch fs will be mounted here
MOUNT_DIR = File.expand_path(File.join(File.dirname(__FILE__), '../app'))

# initialize couchrest database mapper
DB = "http://127.0.0.1:5984/#{DB_NAME}"



class CouchDir < FuseFS::MetaDir
  def initialize(*args)
    @quilt = Quilt.new(DB)
    super
  end

  def file?(path)
    @quilt.file?(path) || super
  end

  def directory?(path)
    @quilt.directory?(path) || super
  end

  def executable?(path)
    @quilt.executable?(path).nil? ? super : false
  end

  def contents(path)
    @quilt.contents(path) + (super || [])
  end

  def read_file(path)
    @quilt.read_file(path) || super
  end

  def can_write?(path)
    true
  end

  def write_to(path, str)
    @quilt.write_to(path, str) || super
  end
end


# main Quilt starts here

# create mount dir unless exists
Dir.mkdir(MOUNT_DIR) unless File.directory?(MOUNT_DIR)

# init couch dir
couchdir = CouchDir.new

FuseFS.set_root(couchdir)
FuseFS.mount_under MOUNT_DIR

trap("INT") do
  puts "ancelling..."
  FuseFS.unmount
  sleep 0.1
  FuseFS.exit
  puts "Bye."
end

puts "Quilt is running on #{MOUNT_DIR}"
FuseFS.run
