#!/usr/bin/env ruby
# Copyright 2010 Johannes J. Schmidt, TF
# 
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
# 
#        http://www.apache.org/licenses/LICENSE-2.0
# 
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#
# usage:
#  quilt http://localhost:5984 ~/quilt

QUILT_ROOT = File.expand_path(File.join(File.dirname(__FILE__), ".."))
require File.join(QUILT_ROOT, "lib/quilt")

# database server url defaults to http://127.0.0.1:5984
# couch fs will be mounted on ./app/127.0.0.1:5984 per default
server     = ARGV[0] || "http://127.0.0.1:5984"
mountpoint = ARGV[1] || File.join(QUILT_ROOT, 'app', File.basename(server))

# create mount point if needed
Dir.mkdir(mountpoint) unless File.directory?(mountpoint)

# init quilt fs
FuseFS.set_root Quilt::QuiltFS.new(server)
FuseFS.mount_under mountpoint

# listen for exit signals and unmount fuse
trap("INT") do
  puts "ancelling..."
  FuseFS.unmount
  FuseFS.exit
  puts "Bye."
end

# actually do the Fuse mount
puts "Quilt maps #{server} to #{mountpoint}"
FuseFS.run
