#!/usr/bin/env ruby
# Copyright 2010 Johannes J. Schmidt, TF
# 
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
# 
#        http://www.apache.org/licenses/LICENSE-2.0
# 
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#
# usage:
# ruby script/quilt http://localhost:5984

QUILT_ROOT = File.expand_path(File.join(File.dirname(__FILE__), ".."))

require File.join(QUILT_ROOT, "lib/quilt")

# specify the database server url here
db = ARGV.first || "http://127.0.0.1:5984"

# couch fs will be mounted here
# eg: app/127.0.0.1:5984
mount_dir = File.join(QUILT_ROOT, 'app', File.basename(db))

# create mount dir unless exists
Dir.mkdir(mount_dir) unless File.directory?(mount_dir)

# init couch dir
couchdir = Quilt.new(db)

FuseFS.set_root(couchdir)
FuseFS.mount_under mount_dir

trap("INT") do
  puts "ancelling..."
  FuseFS.unmount
  FuseFS.exit
  puts "Bye."
end

puts "Quilt maps #{db} to #{mount_dir}"
FuseFS.run
